#!/usr/bin/env tsx
// ============================================================
// Adaptix Ops — Generate Coding Agent Tasks
// ============================================================
// Loads incidents with remediation plans, generates exact
// coding-agent task statements, updates GitHub issues.
// Never invents file paths. Never creates placeholder names.
// ============================================================

import { runPrompt, isModelUnavailable } from "./lib/models.js";
import { loadSnapshot, saveSnapshot } from "./lib/project.js";
import { findOpenIssueByLabel, commentOnIssue } from "./lib/github.js";
import type { CodingAgentTask, ModelStatus } from "./lib/types.js";

const OPS_REPO = "joshuawendorf21310/adaptix-ops";

const NO_DRIFT_RULES = [
  "Do not remove monitored repos from config/repos.json",
  "Do not weaken route contracts",
  "Do not remove required homepage signatures",
  "Do not remove forbidden homepage signatures",
  "HTTP 200 alone is never PASS for route contracts",
  "Do not mark model output as deterministic evidence",
  "Do not close incidents because a model says the issue is fixed",
  "Do not auto-merge production fixes",
  "Do not invent file paths without repo evidence",
  "Do not create placeholder file names",
];

interface RawCodingAgentOutput {
  repo?: string;
  issueTitle?: string;
  taskStatement?: string;
  fileTargets?: string[];
  codeLevelFix?: string[];
  validationCommands?: string[];
  expectedResults?: string[];
  noDriftRules?: string[];
  humanReviewRequired?: boolean;
}

function buildCodingAgentSection(task: CodingAgentTask): string {
  const status = task.modelStatus === "UNKNOWN"
    ? `**Coding Agent Task: UNKNOWN** — ${task.reason ?? "model unavailable"}`
    : `**Coding Agent Task: READY**`;

  return `
## Coding Agent Task

${status}

| Field | Value |
|-------|-------|
| **Repo** | \`${task.repo}\` |
| **Issue Title** | ${task.issueTitle} |
| **Human Review Required** | **${task.humanReviewRequired}** |
| **Generated At** | ${task.generatedAt} |

### Task Statement
${task.taskStatement}

### File Targets
${task.fileTargets.length > 0
  ? task.fileTargets.map((f) => `- \`${f}\``).join("\n")
  : "_No specific files identified. Search the target repo for the relevant route, component, or deploy config before changing code._"}

### Code-Level Fix
${task.codeLevelFix.length > 0
  ? task.codeLevelFix.map((f) => `- ${f}`).join("\n")
  : "_Not specified_"}

### Validation Commands
${task.validationCommands.length > 0
  ? task.validationCommands.map((c) => `\`\`\`bash\n${c}\n\`\`\``).join("\n")
  : "_No validation commands specified_"}

### Expected Results
${task.expectedResults.length > 0
  ? task.expectedResults.map((r) => `- ${r}`).join("\n")
  : "_Not specified_"}

### No-Drift Rules
${task.noDriftRules.map((r) => `- ⚠️ ${r}`).join("\n")}

> **IMPORTANT:** This task was generated by AI. A human must review and approve before merging any production fix.
> The coding agent must not merge production-impacting changes automatically.
`;
}

// ── Main ──────────────────────────────────────────────────────

console.log("\n[generate-coding-agent-task] Loading snapshot...");
const snapshot = loadSnapshot();

const failingIncidents = snapshot.incidents.filter(
  (i) => i.status !== "RESOLVED"
);

const remediationPlans = snapshot.intelligence?.remediationPlans ?? [];

console.log(`[generate-coding-agent-task] ${failingIncidents.length} open incident(s)`);

const codingAgentTasks: CodingAgentTask[] = [];

for (const incident of failingIncidents) {
  const plan = remediationPlans.find((p) => p.contractId === incident.contractId);

  console.log(`[generate-coding-agent-task] Generating task: ${incident.contractId}`);

  const result = await runPrompt<RawCodingAgentOutput>(
    "coding-agent-task.prompt.yml",
    {
      incident: JSON.stringify(incident),
      remediationPlan: JSON.stringify(plan ?? null),
      validationPlan: JSON.stringify(plan?.validationPlan ?? []),
      noDriftRules: JSON.stringify(NO_DRIFT_RULES),
    }
  );

  const generatedAt = new Date().toISOString();

  let task: CodingAgentTask;

  if (isModelUnavailable(result)) {
    task = {
      contractId: incident.contractId,
      modelStatus: "UNKNOWN" as ModelStatus,
      repo: incident.repo,
      issueTitle: `UNKNOWN — model unavailable for ${incident.contractId}`,
      taskStatement: "Model unavailable. Run npm run ai:agent-task when model is accessible.",
      fileTargets: [],
      codeLevelFix: [],
      validationCommands: [incident.validationCommand],
      expectedResults: [incident.expectedResult],
      noDriftRules: NO_DRIFT_RULES,
      humanReviewRequired: true,
      generatedAt,
      reason: result.reason,
    };
  } else {
    task = {
      contractId: incident.contractId,
      modelStatus: "PASS" as ModelStatus,
      repo: result.repo ?? incident.repo,
      issueTitle: result.issueTitle ?? `Fix: ${incident.failureTitle}`,
      taskStatement: result.taskStatement ?? "No task statement generated",
      fileTargets: result.fileTargets ?? [],
      codeLevelFix: result.codeLevelFix ?? [],
      validationCommands: result.validationCommands ?? [incident.validationCommand],
      expectedResults: result.expectedResults ?? [incident.expectedResult],
      noDriftRules: [...NO_DRIFT_RULES, ...(result.noDriftRules ?? [])],
      humanReviewRequired: result.humanReviewRequired ?? true,
      generatedAt,
      rawModelOutput: result,
    };
  }

  codingAgentTasks.push(task);
  console.log(`[generate-coding-agent-task] ${incident.contractId} → ${task.modelStatus}`);

  // Update GitHub issue
  if (incident.issueNumber) {
    try {
      const existing = await findOpenIssueByLabel(OPS_REPO, incident.contractId);
      if (existing) {
        const section = buildCodingAgentSection(task);
        await commentOnIssue(OPS_REPO, existing.number, section);
        console.log(`[generate-coding-agent-task] Updated issue #${existing.number}`);
      }
    } catch (err) {
      console.warn(`[generate-coding-agent-task] Failed to update issue:`, err);
    }
  }
}

// Update snapshot
const updatedSnapshot = {
  ...snapshot,
  intelligence: {
    ...snapshot.intelligence,
    codingAgentTasks,
  },
  generatedAt: new Date().toISOString(),
};

saveSnapshot(updatedSnapshot);
console.log(`\n[generate-coding-agent-task] Done. ${codingAgentTasks.length} task(s) saved.`);
